### ISSUE TITLE
1.8.8 Server Issues

### ISSUE THREAD

**Issue by HowardZHY** [flrping/Economobs#14]
I believe these errors happens on other paper forks as well.

1.The method doesn't exists on 1.8, use the deprecated method below it:

`[20:11:33] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Economobs v2.2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BurritoSpigot.jar:git-BurritoSpigot-c98328e]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[BurritoSpigot.jar:git-BurritoSpigot-c98328e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BurritoSpigot.jar:git-BurritoSpigot-c98328e]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInMainHand()Lorg/bukkit/inventory/ItemStack;
	at dev.flrp.economobs.manager.RewardManager.calculateMultiplier(RewardManager.java:104) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.handleEconomyReward(RewardManager.java:491) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.handleSingleLootReward(RewardManager.java:472) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.handleLootReward(RewardManager.java:452) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.handleLootReward(RewardManager.java:443) ~[?:?]
	at dev.flrp.economobs.listener.PlayerListener.onPlayerDeath(PlayerListener.java:37) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[BurritoSpigot.jar:git-BurritoSpigot-c98328e]
	... 23 more`
	
2. 
`[21:08:48] [Server thread/WARN]: Plugin Economobs v2.2.1 tried to register permission 'economobs.profile' but it's already registered
java.lang.IllegalArgumentException: The permission economobs.profile is already defined!
[21:08:48] [Server thread/WARN]: Plugin Economobs v2.2.1 tried to register permission 'economobs.check' but it's already registered
java.lang.IllegalArgumentException: The permission economobs.check is already defined!
[21:08:48] [Server thread/WARN]: Plugin Economobs v2.2.1 tried to register permission 'economobs.multiplier' but it's already registered
java.lang.IllegalArgumentException: The permission economobs.multiplier is already defined!
[21:08:48] [Server thread/WARN]: Plugin Economobs v2.2.1 tried to register permission 'economobs.reload' but it's already registered
java.lang.IllegalArgumentException: The permission economobs.reload is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:365) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]`
	
And this might cause 3:

`21:19:03] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Economobs v2.2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	...
	Caused by: java.lang.NullPointerException
        at dev.flrp.economobs.manager.MultiplierManager.getMultiplierGroup(MultiplierManager.java:38) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.getEntityMultiplier(RewardManager.java:110) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.calculateMultiplier(RewardManager.java:91) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.handleEconomyReward(RewardManager.java:491) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.handleSingleLootReward(RewardManager.java:472) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.handleLootReward(RewardManager.java:452) ~[?:?]
	at dev.flrp.economobs.manager.RewardManager.handleLootReward(RewardManager.java:443) ~[?:?]
	at dev.flrp.economobs.listener.EntityDeathListener.onMobDeath(EntityDeathListener.java:62) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor285.invoke(Unknown Source) ~[?:?]`

**Comment by HowardZHY** [comment]
Thanks, and the third one seems caused by config mistake that when `multipliers` doesn't have `weapons`

**Comment by flrping** [comment]
Can you show your configuration for groups?

**Comment by HowardZHY** [comment]
> Can you show your configuration for groups?

`  1:
    weight: 1
    mobs:
      - ZOMBIE 2.0
    weapons:
      - DIAMOND_SWORD 2.0`
     
if `weapons:` was removed

**Comment by HowardZHY** [comment]
There's a new error, when a citizens npc / sentinel kill mobs:
`[14:42:43] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Economobs v2.2.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:886) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityZombie.die(EntityZombie.java:561) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:824) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityZombie.damageEntity(EntityZombie.java:167) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:261) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1655) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1622) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1459) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:848) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException: null`

(no more stacktrace after)
