### ISSUE TITLE
Sentinel Error

### ISSUE THREAD

**Issue by flrping** [flrping/Economobs#16]
There's a new error, when a citizens npc / sentinel kill mobs:
`[14:42:43] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Economobs v2.2.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:886) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityZombie.die(EntityZombie.java:561) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:824) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityZombie.damageEntity(EntityZombie.java:167) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:261) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1655) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1622) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1459) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:848) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [BurritoSpigot.jar:git-BurritoSpigot-0f3fbe0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException: null`

(no more stacktrace after)

_Originally posted by @HowardZHY in https://github.com/flrping/Economobs/issues/14#issuecomment-2509601462_

**Comment by HowardZHY** [comment]
I have these stacktrace with try-catch onMobDeath

`[23:44:10] [Server thread/WARN]: java.lang.NullPointerException
[23:44:10] [Server thread/WARN]: 	at dev.flrp.economobs.manager.MultiplierManager.getMultiplierGroup(MultiplierManager.java:38)
[23:44:10] [Server thread/WARN]: 	at dev.flrp.economobs.manager.RewardManager.getEntityMultiplier(RewardManager.java:111)
[23:44:10] [Server thread/WARN]: 	at dev.flrp.economobs.manager.RewardManager.calculateMultiplier(RewardManager.java:92)
[23:44:10] [Server thread/WARN]: 	at dev.flrp.economobs.manager.RewardManager.handleEconomyReward(RewardManager.java:492)
[23:44:10] [Server thread/WARN]: 	at dev.flrp.economobs.manager.RewardManager.handleSingleLootReward(RewardManager.java:473)
[23:44:10] [Server thread/WARN]: 	at dev.flrp.economobs.manager.RewardManager.handleLootReward(RewardManager.java:453)
[23:44:10] [Server thread/WARN]: 	at dev.flrp.economobs.manager.RewardManager.handleLootReward(RewardManager.java:444)
[23:44:10] [Server thread/WARN]: 	at dev.flrp.economobs.listener.EntityDeathListener.onMobDeath(EntityDeathListener.java:74)`

https://github.com/flrping/Economobs/blob/6ae99fc9421fb7b4525b9241e60f687f0c935773/src/main/java/dev/flrp/economobs/manager/MultiplierManager.java#L38

This is null if it's a NPC

**Comment by HowardZHY** [comment]
@flrping 
I think nullcheck getPlayer should fix
`
    public MultiplierGroup getMultiplierGroup(UUID uuid) {
        String group = null;
        int weight = 0;
        Player p = Bukkit.getPlayer(uuid);
        Set<PermissionAttachmentInfo> infoSet = p.getEffectivePermissions();
        if (p != null) {
        ...
 `

**Comment by flrping** [comment]
There is a dedicated sentinel hook that should work. I'll take a look at this later on today. Can you tell me your sentinel version?

**Comment by flrping** [comment]
What is your Citizens version?

**Comment by HowardZHY** [comment]
Citizens v2.0.35-SNAPSHOT (build 3478) 
Last one with 1.8 support
