### ISSUE TITLE
MythicMobs Disables Ecomomobs in 1.19

### ISSUE THREAD

**Issue by ShermansWorld** [flrping/Economobs#2]
Server Jar: Paper 1.19
Economobs Version: 1.4.0
MythicMobs Version: 5.1.0-SNAPSHOT

Hello. I get the following error on my server when Economobs tries to enable its hooks for Mythicsmobs. I will say as a developer myself I've had similar issues with MythicsMobs. They occasionally change package and class names and it totally screws up compatibility with other plugins. Updating your references should fix this, let me know if I can do anything to help.

[17:05:30] [Server thread/INFO]: [Economobs] Enabling Economobs v1.4.0
[17:05:30] [Server thread/INFO]: [Economobs] --------------
[17:05:30] [Server thread/INFO]: [Economobs] Economobs by flrp (v1.4.0)
[17:05:30] [Server thread/INFO]: [Economobs] Consider Patreon to support me for keeping these plugins free.
[17:05:30] [Server thread/INFO]: [Economobs] --------------
[17:05:30] [Server thread/INFO]: [Economobs] Starting...
[17:05:30] [Server thread/INFO]: [Economobs] Loaded 77 mob values.
[17:05:30] [Server thread/INFO]: [Economobs] Message Type: ACTION_BAR
[17:05:30] [Server thread/INFO]: [Economobs] Loaded 3 multiplier groups.
[17:05:30] [Server thread/INFO]: [Economobs] Found stacker plugin StackMob. Registered Events.
[17:05:30] [Server thread/INFO]: [Economobs] Starting to register hooks. Please wait.
[17:05:30] [Server thread/INFO]: [Economobs] Vault found. Attempting to hook.
[17:05:30] [Server thread/ERROR]: Error occurred while enabling Economobs v1.4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
	at dev.flrp.economobs.hooks.MythicMobsHook.<clinit>(MythicMobsHook.java:17) ~[Economobs-1.4.0.jar:?]
	at dev.flrp.economobs.managers.HookManager.load(HookManager.java:23) ~[Economobs-1.4.0.jar:?]
	at dev.flrp.economobs.managers.HookManager.<init>(HookManager.java:16) ~[Economobs-1.4.0.jar:?]
	at dev.flrp.economobs.Economobs.onEnable(Economobs.java:67) ~[Economobs-1.4.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-58]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 15 more
[17:05:30] [Server thread/INFO]: [Economobs] Disabling Economobs v1.4.0
[17:05:30] [Server thread/ERROR]: Error occurred while disabling Economobs v1.4.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.flrp.economobs.managers.DatabaseManager.close()" because "this.databaseManager" is null
	at dev.flrp.economobs.Economobs.onDisable(Economobs.java:103) ~[Economobs-1.4.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:573) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-58]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by flrping** [comment]
Didn't see this, but thanks for reporting. I have fixed this, and it will be available in the next update (1.4.2).
